project:
  type: website
  output-dir: docs
website:
  title: "John Pinto"
  site-url: https://johnppinto.github.io/blog
  description: "This is John Pinto's Personal Blog."
  search: 
    location: navbar
    type: textbox
  navbar:
    left: 
      - text: Blog
        href: blog.qmd
      - text: About
        href: about.qmd
      - text: Portfolio
        href: https://johnppinto.github.io/
        target: _blank
    right:
      - icon: github
        href: https://github.com/JohnPPinto
        target: _blank
      - icon: linkedin
        href: https://www.linkedin.com/in/john-p-pinto/
        target: _blank
      - icon: medium
        href: https://medium.com/@pintojohn47
        target: _blank
      - icon: twitter
        href: https://twitter.com/john77272002
        target: _blank
      - icon: rss
        href: blog.xml
        target: _blank
  google-analytics: <enter here>
  cookie-consent: true
  twitter-card: true
  open-graph: true
  page-footer: 
    left: John Pinto {{< fa copyright regular >}} 2023 made with HTML5 <i class="fab fa-html5"></i>, CSS3 <i class="fa-brands fa-css3"></i> and [Quarto](https://quarto.org).
highlight-style: arrow
format:
  html:
    mainfont: "Book Antiqua"
    fontsize: 18px
    theme:
      dark: superhero
      light: flatly
    css: styles.css
    code-block-bg: true
    code-block-border-left: "#31BAE9"